services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://local:local@mongo:27017/employees?authSource=admin
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:6
    container_name: docker-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'local'
      MONGO_INITDB_ROOT_PASSWORD: 'local'
    ports:
      - '27017:27017'
